### ISSUE TITLE
Saltstack Community Repo

### ISSUE THREAD

**Issue by philippkahr** [XITASO/sonarqube-formula#1]
Hallo Xitaso,

would it be ok to fork your formula into the Saltstack community repo?
https://github.com/saltstack-formulas would be nice to have it in there too.

**Comment by corux** [comment]
Hello!
The reason, the formula is not yet under the hood of @saltstack-formulas, is the hardcoded dependency to the formula [corux/java-formula](https://github.com/corux/java-formula).
As soon as this dependency is removed or updated to the official [saltstack-formulas/sun-java-formula](https://github.com/saltstack-formulas/sun-java-formula), we will transfer the repo to @saltstack-formulas.

Best regards, Tobias
